version: '3.6'
networks:
  overlay:
volumes:
  db-data:
  db2-data:
services:
  proxy:
    image: traefik:1.6
    command: |-
      -c /dev/null
      --docker
      --docker.watch
      --docker.exposedByDefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - overlay
    ports:
      - 80:80
  backend:
    build: ./backend
    networks:
      - overlay
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:dkzp-backend.local
    volumes:
      - ./backend:/var/www
      - ./backend/docker/etc/apache2/sites-enabled:/etc/apache2/sites-enabled
    environment:
      DATABASE_URL: mysql://root:root@db:3306/test
  # frontend:
  #   build: ./frontend
  #   networks:
  #     - overlay
  #   labels:
  #     - traefik.enable=true
  #     - traefik.port=80
  #     - traefik.frontend.rule=Host:dkzp-frontend.local
  #   volumes:
  #     - ./frontend:/app
  db:
    image: mariadb:10.3
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - overlay
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - 3306:3306
  db2:
    image: mariadb:10.3
    volumes:
      - db2-data:/var/lib/mysql
      - ./pok.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - overlay
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - 3307:3306
