version: '3.4'
networks:
  overlay:
volumes:
  db-data:
services:
  proxy:
    image: traefik:1.6
    command: |-
      -c /dev/null
      --docker
      --docker.watch
      --docker.exposedByDefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - overlay
    ports:
      - 80:80
  backend:
    build: ./backend
    networks:
      - overlay
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:dkzp-backend.local
    volumes:
      - ./backend:/var/www
    environment:
      DATABASE_URL: mysql://test:test@db:3306/test
  # frontend:
  #   build: ./frontend
  #   networks:
  #     - overlay
  #   labels:
  #     - traefik.enable=true
  #     - traefik.port=80
  #     - traefik.frontend.rule=Host:dkzp-frontend.local
  #   volumes:
  #     - ./frontend:/app
  db:
    image: mariadb:10.3
    volumes:
     - db-data:/var/lib/mysql
    networks:
      - overlay
    restart: always
    ports:
      - 3306:3306
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: test
     MYSQL_USER: test
     MYSQL_PASSWORD: test
