export { default as HomePage } from './HomePage'
export { default as AuthorsPage } from './AuthorsPage'
export { default as ContactPage } from './ContactPage'
export { default as CategoriesPage } from './CategoriesPage'
export { default as FavoriteBooksPage } from './FavoriteBooksPage'
export { default as NewBooksPage } from './NewBooksPage'